version: '3'
services:
  hdfs:
    build:
      context: ./docker/hdfs
      dockerfile: Dockerfile
      args:
        - HDFS_VERSION=2.8.2
    networks:
      - pegasus-nw
    image: hdfs
    ports:
    - 9020:9020
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    container_name: hdfs-box
    hostname: hdfs-box
    stdin_open: true
    tty: true
  hive:
    depends_on:
      - "hdfs"
    build:
      context: ./docker/hive
      dockerfile: Dockerfile
      args:
        - HIVE_VERSION=1.1.0
    networks:
      - pegasus-nw
    container_name: hive-box
    hostname: hive-box
    stdin_open: true
    image: hive
    tty: true
    ports:
      - 10000:10000
      - 9083:9083
  pegasus-master:
    depends_on:
      - "hive"
    build:
      context: .
      dockerfile: docker/pegasus/Dockerfile
    image: pegasus
    networks:
      - pegasus-nw
    container_name: pegasus-master
    hostname: pegasus-master
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: pegasus-nw
  pegasus-nw:
    driver: bridge
